module.exports = {
  command:"ping",
  description: "Displays the bot's ping",
  syntax: ")>ping",
  category: "Utility",
  permission: "sendMessages",
  botPermission: "embedLinks",
  execute: async (meteor, bot, msg, args) => {
    let pinging = [
      "Russia",
      "the USA",
      "Ken's mom's house",
      "Hig",
      "Newt's snapchat",
      "your dead server",
      "discordapp.com",
      "youtube.com",
      "the suicide hotlines",
      "NotSoBot",
      "SpaceX's starman",
      "Logan Paul",
      "Post Malone",
      "Donald Trump",
      "a bad soundcloud rapper",
      "hentai haven",
      "Solace",
      "your mom",
      "ringa ding",
      "a shitty teen house party",
      "the crackhouse on 17th street",
      "https://",
      "Pixilia",
      "twitter dot com",
      "the local abortion clinic",
      "the middle east",
      "my pug named Bazooka",
      "Runescape",
      "the pentagon",
      "the middle of Australia",
      "Africa",
      "Toto - Africa",
      "Jake Paul",
      "the Logangers",
      "the Jake Paulers",
      "Alex Jones' tinfoil hat",
      "the ISS",
      "ISIS",
      "Tupac",
      "the dark side of the moon",
      "Chou Tzuyu",
      "a group of juggalos",
      "Hopsin fans",
      "Eminem",
      "discordbots.org",
      "the Bee Movie",
      "some discord server raiders",
      "Ookla speed tests",
      "Comcast",
      "Discord's API 10000 times",
      "Owen Wilson's nose",
      "superiorservers",
      "my girlfriend's massive cock",
      "Meteor oh nanaananananaananan",
      "AT&T",
      "b1nzy",
      "b1nzy's cat",
      "hypesquad",
      "my dad",
      "aaaaaaaaaaaaa",
      "random short bald man stuck in traffic",
      "Discord T&S",
      "Luke Skywalker",
      "Donald Trump's wife",
      "Zelensky",
      "Earth",
      "Elon Musk's anime server",
      "medal.tv"
    ]
    let botPing = Math.floor(msg.channel.guild.shard.latency);
    let ran = Math.floor(Math.random() * pinging.length);
    await msg.channel.createMessage({embed: {
      color:0x36393E, description: `:satellite_orbital: Took **${botPing}ms** to ping ${pinging[ran]}`
    }});
  }
}